import type { EmployeeFormTemplate } from "@shared/schema";

export function createDefaultEmployeeFormTemplate(): EmployeeFormTemplate {
  const now = new Date().toISOString();
  const templateId = crypto.randomUUID();
  
  return {
    id: templateId,
    name: "Standard Employee Onboarding Form",
    description: "Comprehensive UK employee onboarding form with immigration status tracking and compliance automation",
    version: 13,
    isActive: true,
    steps: [
      {
        id: "step-1-basic",
        title: "Basic Details",
        description: "Personal and employment information",
        order: 1,
      },
      {
        id: "step-2-status",
        title: "Nationality & Status",
        description: "Immigration status determination",
        order: 2,
      },
      {
        id: "step-3-conditional",
        title: "Immigration Details",
        description: "Status-specific information and documentation",
        order: 3,
      },
      {
        id: "step-4-compliance",
        title: "Compliance & Documents",
        description: "Probation, status tracking, and document management",
        order: 4,
      },
    ],
    fields: [
      // =========================================
      // STEP 1: BASIC DETAILS (always shown)
      // =========================================
      
      // Personal Information Section
      {
        id: "header-personal",
        name: "header_personal",
        label: "Personal Information",
        type: "section_header",
        step: 1,
        order: 1,
        width: "full",
      },
      {
        id: "field-first-name",
        name: "firstName",
        label: "First Name",
        type: "text",
        required: true,
        step: 1,
        order: 2,
        width: "half",
      },
      {
        id: "field-middle-names",
        name: "middleNames",
        label: "Middle Names",
        type: "text",
        required: false,
        placeholder: "Leave blank if none",
        step: 1,
        order: 2.5,
        width: "half",
      },
      {
        id: "field-last-name",
        name: "lastName",
        label: "Last Name",
        type: "text",
        required: true,
        step: 1,
        order: 3,
        width: "half",
      },
      {
        id: "field-dob",
        name: "dateOfBirth",
        label: "Date of Birth",
        type: "date",
        required: true,
        step: 1,
        order: 4,
        width: "half",
      },
      {
        id: "field-mobile",
        name: "personalMobile",
        label: "Personal Mobile",
        type: "tel",
        required: true,
        step: 1,
        order: 5,
        width: "half",
      },
      {
        id: "field-email",
        name: "personalEmail",
        label: "Personal Email",
        type: "email",
        required: true,
        step: 1,
        order: 6,
        width: "full",
      },
      {
        id: "field-nationality",
        name: "nationality",
        label: "Nationality",
        type: "select",
        required: true,
        helperText: "Country of citizenship (required for all employees)",
        options: [
          { label: "Afghanistan", value: "Afghanistan" },
          { label: "Albania", value: "Albania" },
          { label: "Algeria", value: "Algeria" },
          { label: "Andorra", value: "Andorra" },
          { label: "Angola", value: "Angola" },
          { label: "Argentina", value: "Argentina" },
          { label: "Armenia", value: "Armenia" },
          { label: "Australia", value: "Australia" },
          { label: "Austria", value: "Austria" },
          { label: "Azerbaijan", value: "Azerbaijan" },
          { label: "Bahamas", value: "Bahamas" },
          { label: "Bahrain", value: "Bahrain" },
          { label: "Bangladesh", value: "Bangladesh" },
          { label: "Barbados", value: "Barbados" },
          { label: "Belarus", value: "Belarus" },
          { label: "Belgium", value: "Belgium" },
          { label: "Belize", value: "Belize" },
          { label: "Benin", value: "Benin" },
          { label: "Bhutan", value: "Bhutan" },
          { label: "Bolivia", value: "Bolivia" },
          { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
          { label: "Botswana", value: "Botswana" },
          { label: "Brazil", value: "Brazil" },
          { label: "Brunei", value: "Brunei" },
          { label: "Bulgaria", value: "Bulgaria" },
          { label: "Burkina Faso", value: "Burkina Faso" },
          { label: "Burundi", value: "Burundi" },
          { label: "Cambodia", value: "Cambodia" },
          { label: "Cameroon", value: "Cameroon" },
          { label: "Canada", value: "Canada" },
          { label: "Cape Verde", value: "Cape Verde" },
          { label: "Central African Republic", value: "Central African Republic" },
          { label: "Chad", value: "Chad" },
          { label: "Chile", value: "Chile" },
          { label: "China", value: "China" },
          { label: "Colombia", value: "Colombia" },
          { label: "Comoros", value: "Comoros" },
          { label: "Congo", value: "Congo" },
          { label: "Costa Rica", value: "Costa Rica" },
          { label: "Croatia", value: "Croatia" },
          { label: "Cuba", value: "Cuba" },
          { label: "Cyprus", value: "Cyprus" },
          { label: "Czech Republic", value: "Czech Republic" },
          { label: "Denmark", value: "Denmark" },
          { label: "Djibouti", value: "Djibouti" },
          { label: "Dominica", value: "Dominica" },
          { label: "Dominican Republic", value: "Dominican Republic" },
          { label: "Ecuador", value: "Ecuador" },
          { label: "Egypt", value: "Egypt" },
          { label: "El Salvador", value: "El Salvador" },
          { label: "Equatorial Guinea", value: "Equatorial Guinea" },
          { label: "Eritrea", value: "Eritrea" },
          { label: "Estonia", value: "Estonia" },
          { label: "Ethiopia", value: "Ethiopia" },
          { label: "Fiji", value: "Fiji" },
          { label: "Finland", value: "Finland" },
          { label: "France", value: "France" },
          { label: "Gabon", value: "Gabon" },
          { label: "Gambia", value: "Gambia" },
          { label: "Georgia", value: "Georgia" },
          { label: "Germany", value: "Germany" },
          { label: "Ghana", value: "Ghana" },
          { label: "Greece", value: "Greece" },
          { label: "Grenada", value: "Grenada" },
          { label: "Guatemala", value: "Guatemala" },
          { label: "Guinea", value: "Guinea" },
          { label: "Guinea-Bissau", value: "Guinea-Bissau" },
          { label: "Guyana", value: "Guyana" },
          { label: "Haiti", value: "Haiti" },
          { label: "Honduras", value: "Honduras" },
          { label: "Hungary", value: "Hungary" },
          { label: "Iceland", value: "Iceland" },
          { label: "India", value: "India" },
          { label: "Indonesia", value: "Indonesia" },
          { label: "Iran", value: "Iran" },
          { label: "Iraq", value: "Iraq" },
          { label: "Ireland", value: "Ireland" },
          { label: "Israel", value: "Israel" },
          { label: "Italy", value: "Italy" },
          { label: "Ivory Coast", value: "Ivory Coast" },
          { label: "Jamaica", value: "Jamaica" },
          { label: "Japan", value: "Japan" },
          { label: "Jordan", value: "Jordan" },
          { label: "Kazakhstan", value: "Kazakhstan" },
          { label: "Kenya", value: "Kenya" },
          { label: "Kiribati", value: "Kiribati" },
          { label: "Kuwait", value: "Kuwait" },
          { label: "Kyrgyzstan", value: "Kyrgyzstan" },
          { label: "Laos", value: "Laos" },
          { label: "Latvia", value: "Latvia" },
          { label: "Lebanon", value: "Lebanon" },
          { label: "Lesotho", value: "Lesotho" },
          { label: "Liberia", value: "Liberia" },
          { label: "Libya", value: "Libya" },
          { label: "Liechtenstein", value: "Liechtenstein" },
          { label: "Lithuania", value: "Lithuania" },
          { label: "Luxembourg", value: "Luxembourg" },
          { label: "Madagascar", value: "Madagascar" },
          { label: "Malawi", value: "Malawi" },
          { label: "Malaysia", value: "Malaysia" },
          { label: "Maldives", value: "Maldives" },
          { label: "Mali", value: "Mali" },
          { label: "Malta", value: "Malta" },
          { label: "Marshall Islands", value: "Marshall Islands" },
          { label: "Mauritania", value: "Mauritania" },
          { label: "Mauritius", value: "Mauritius" },
          { label: "Mexico", value: "Mexico" },
          { label: "Micronesia", value: "Micronesia" },
          { label: "Moldova", value: "Moldova" },
          { label: "Monaco", value: "Monaco" },
          { label: "Mongolia", value: "Mongolia" },
          { label: "Montenegro", value: "Montenegro" },
          { label: "Morocco", value: "Morocco" },
          { label: "Mozambique", value: "Mozambique" },
          { label: "Myanmar", value: "Myanmar" },
          { label: "Namibia", value: "Namibia" },
          { label: "Nauru", value: "Nauru" },
          { label: "Nepal", value: "Nepal" },
          { label: "Netherlands", value: "Netherlands" },
          { label: "New Zealand", value: "New Zealand" },
          { label: "Nicaragua", value: "Nicaragua" },
          { label: "Niger", value: "Niger" },
          { label: "Nigeria", value: "Nigeria" },
          { label: "North Korea", value: "North Korea" },
          { label: "North Macedonia", value: "North Macedonia" },
          { label: "Norway", value: "Norway" },
          { label: "Oman", value: "Oman" },
          { label: "Pakistan", value: "Pakistan" },
          { label: "Palau", value: "Palau" },
          { label: "Palestine", value: "Palestine" },
          { label: "Panama", value: "Panama" },
          { label: "Papua New Guinea", value: "Papua New Guinea" },
          { label: "Paraguay", value: "Paraguay" },
          { label: "Peru", value: "Peru" },
          { label: "Philippines", value: "Philippines" },
          { label: "Poland", value: "Poland" },
          { label: "Portugal", value: "Portugal" },
          { label: "Qatar", value: "Qatar" },
          { label: "Romania", value: "Romania" },
          { label: "Russia", value: "Russia" },
          { label: "Rwanda", value: "Rwanda" },
          { label: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
          { label: "Saint Lucia", value: "Saint Lucia" },
          { label: "Saint Vincent and the Grenadines", value: "Saint Vincent and the Grenadines" },
          { label: "Samoa", value: "Samoa" },
          { label: "San Marino", value: "San Marino" },
          { label: "Sao Tome and Principe", value: "Sao Tome and Principe" },
          { label: "Saudi Arabia", value: "Saudi Arabia" },
          { label: "Senegal", value: "Senegal" },
          { label: "Serbia", value: "Serbia" },
          { label: "Seychelles", value: "Seychelles" },
          { label: "Sierra Leone", value: "Sierra Leone" },
          { label: "Singapore", value: "Singapore" },
          { label: "Slovakia", value: "Slovakia" },
          { label: "Slovenia", value: "Slovenia" },
          { label: "Solomon Islands", value: "Solomon Islands" },
          { label: "Somalia", value: "Somalia" },
          { label: "South Africa", value: "South Africa" },
          { label: "South Korea", value: "South Korea" },
          { label: "South Sudan", value: "South Sudan" },
          { label: "Spain", value: "Spain" },
          { label: "Sri Lanka", value: "Sri Lanka" },
          { label: "Sudan", value: "Sudan" },
          { label: "Suriname", value: "Suriname" },
          { label: "Sweden", value: "Sweden" },
          { label: "Switzerland", value: "Switzerland" },
          { label: "Syria", value: "Syria" },
          { label: "Taiwan", value: "Taiwan" },
          { label: "Tajikistan", value: "Tajikistan" },
          { label: "Tanzania", value: "Tanzania" },
          { label: "Thailand", value: "Thailand" },
          { label: "Timor-Leste", value: "Timor-Leste" },
          { label: "Togo", value: "Togo" },
          { label: "Tonga", value: "Tonga" },
          { label: "Trinidad and Tobago", value: "Trinidad and Tobago" },
          { label: "Tunisia", value: "Tunisia" },
          { label: "Turkey", value: "Turkey" },
          { label: "Turkmenistan", value: "Turkmenistan" },
          { label: "Tuvalu", value: "Tuvalu" },
          { label: "Uganda", value: "Uganda" },
          { label: "Ukraine", value: "Ukraine" },
          { label: "United Arab Emirates", value: "United Arab Emirates" },
          { label: "United Kingdom", value: "United Kingdom" },
          { label: "United States", value: "United States" },
          { label: "Uruguay", value: "Uruguay" },
          { label: "Uzbekistan", value: "Uzbekistan" },
          { label: "Vanuatu", value: "Vanuatu" },
          { label: "Vatican City", value: "Vatican City" },
          { label: "Venezuela", value: "Venezuela" },
          { label: "Vietnam", value: "Vietnam" },
          { label: "Yemen", value: "Yemen" },
          { label: "Zambia", value: "Zambia" },
          { label: "Zimbabwe", value: "Zimbabwe" },
        ],
        step: 1,
        order: 6.5,
        width: "half",
      },
      {
        id: "field-passport-number",
        name: "passportNumber",
        label: "Passport Number",
        type: "text",
        required: true,
        helperText: "Required for all employees",
        step: 1,
        order: 6.6,
        width: "half",
      },
      {
        id: "field-passport-expiry",
        name: "passportExpiry",
        label: "Passport Expiry Date",
        type: "date",
        required: true,
        helperText: "Required for all employees",
        step: 1,
        order: 6.7,
        width: "half",
      },
      
      // Address Section
      {
        id: "header-address",
        name: "header_address",
        label: "Address",
        type: "section_header",
        step: 1,
        order: 7,
        width: "full",
      },
      {
        id: "field-uk-address-later",
        name: "ukAddressProvideLater",
        label: "UK Address - Provide Now or Later?",
        type: "select",
        helperText: "Select 'Providing now' and fill address below, or choose when you'll provide it",
        defaultValue: "providing_now",
        options: [
          { label: "Providing now", value: "providing_now" },
          { label: "In 1 week", value: "1_week" },
          { label: "In 2 weeks", value: "2_weeks" },
          { label: "In 3 weeks", value: "3_weeks" },
          { label: "In 4 weeks", value: "4_weeks" },
          { label: "In 5 weeks", value: "5_weeks" },
          { label: "In 6 weeks", value: "6_weeks" },
        ],
        step: 1,
        order: 8,
        width: "full",
      },
      {
        id: "field-uk-address",
        name: "ukAddress",
        label: "UK Address",
        type: "textarea",
        helperText: "Required if 'Providing now' is selected above",
        step: 1,
        order: 9,
        width: "full",
      },
      {
        id: "field-overseas-address",
        name: "overseasAddress",
        label: "Overseas Address",
        type: "textarea",
        required: true,
        helperText: "Current/permanent overseas address (required)",
        step: 1,
        order: 10,
        width: "full",
      },
      {
        id: "field-uk-bank-details",
        name: "ukBankDetails",
        label: "UK Bank Details",
        type: "textarea",
        helperText: "Provide now or select a timeframe below",
        step: 1,
        order: 11,
        width: "full",
      },
      {
        id: "field-uk-bank-details-later",
        name: "ukBankDetailsProvideLater",
        label: "Provide UK Bank Details Later",
        type: "select",
        helperText: "If not providing now, select when you'll provide it",
        defaultValue: "providing_now",
        options: [
          { label: "Providing now", value: "providing_now" },
          { label: "In 1 week", value: "1_week" },
          { label: "In 2 weeks", value: "2_weeks" },
          { label: "In 3 weeks", value: "3_weeks" },
          { label: "In 4 weeks", value: "4_weeks" },
          { label: "In 5 weeks", value: "5_weeks" },
          { label: "In 6 weeks", value: "6_weeks" },
        ],
        step: 1,
        order: 12,
        width: "half",
      },
      
      // Emergency Contact Section (ALL MANDATORY)
      {
        id: "header-emergency",
        name: "header_emergency",
        label: "Emergency Contact (Required)",
        type: "section_header",
        step: 1,
        order: 13,
        width: "full",
      },
      {
        id: "field-emergency-name",
        name: "emergencyContactName",
        label: "Contact Name",
        type: "text",
        required: true,
        step: 1,
        order: 14,
        width: "full",
      },
      {
        id: "field-emergency-relationship",
        name: "emergencyContactRelationship",
        label: "Relationship",
        type: "text",
        required: true,
        step: 1,
        order: 15,
        width: "half",
      },
      {
        id: "field-emergency-phone",
        name: "emergencyContactPhone",
        label: "Contact Phone",
        type: "tel",
        required: true,
        step: 1,
        order: 16,
        width: "half",
      },
      
      // Employment Details Section
      {
        id: "header-employment",
        name: "header_employment",
        label: "Employment Details",
        type: "section_header",
        step: 1,
        order: 17,
        width: "full",
      },
      {
        id: "field-company",
        name: "companyId",
        label: "Company",
        type: "select",
        required: true,
        helperText: "Select the company this employee will work for",
        step: 1,
        order: 18,
        width: "full",
      },
      {
        id: "field-department",
        name: "department",
        label: "Department",
        type: "select",
        options: [
          { label: "Business development", value: "business_development" },
          { label: "Marketing / Sales / Export", value: "marketing_sales_export" },
          { label: "Administration", value: "administration" },
          { label: "HR", value: "hr" },
          { label: "Finance", value: "finance" },
          { label: "Technical", value: "technical" },
        ],
        step: 1,
        order: 19,
        width: "half",
      },
      {
        id: "field-work-location",
        name: "workLocation",
        label: "Work Location",
        type: "select",
        required: true,
        helperText: "Select company registered address or SL work address",
        options: [], // Will be populated dynamically based on selected company
        step: 1,
        order: 20,
        width: "half",
      },
      {
        id: "field-line-manager",
        name: "lineManager",
        label: "Line Manager",
        type: "text",
        required: true,
        step: 1,
        order: 21,
        width: "half",
      },
      {
        id: "field-job-title",
        name: "jobTitle",
        label: "Job Title",
        type: "text",
        required: true,
        step: 1,
        order: 22,
        width: "half",
      },
      {
        id: "field-job-description",
        name: "jobDescription",
        label: "Job Description",
        type: "textarea",
        required: true,
        helperText: "Brief description of role and responsibilities (up to 2000 characters)",
        maxLength: 2000,
        step: 1,
        order: 23,
        width: "full",
      },
      {
        id: "field-contract-type",
        name: "contractType",
        label: "Contract Type",
        type: "select",
        required: true,
        options: [
          { label: "Permanent", value: "permanent" },
          { label: "Fixed-term", value: "fixed_term" },
          { label: "Contractor", value: "contractor" },
        ],
        step: 1,
        order: 24,
        width: "half",
      },
      {
        id: "field-start-date",
        name: "startDate",
        label: "Start Date",
        type: "date",
        required: true,
        step: 1,
        order: 25,
        width: "half",
      },
      {
        id: "field-end-date",
        name: "endDate",
        label: "End Date",
        type: "date",
        helperText: "Required for Fixed-term contracts",
        step: 1,
        order: 26,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-end-date",
            triggerFieldId: "field-contract-type",
            operator: "equals",
            value: "fixed_term",
            action: "show",
            targetFieldIds: ["field-end-date"],
          },
        ],
      },
      {
        id: "field-working-days-preset",
        name: "workingDaysPreset",
        label: "Working Days",
        type: "select",
        required: true,
        defaultValue: "mon-fri",
        options: [
          { label: "Mon-Fri (Standard)", value: "mon-fri" },
          { label: "Custom Days", value: "custom" },
        ],
        step: 1,
        order: 26.5,
        width: "half",
      },
      {
        id: "field-working-days",
        name: "workingDays",
        label: "Select Working Days",
        type: "checkbox_group",
        helperText: "Select the days this employee works",
        options: [
          { label: "Monday", value: "monday" },
          { label: "Tuesday", value: "tuesday" },
          { label: "Wednesday", value: "wednesday" },
          { label: "Thursday", value: "thursday" },
          { label: "Friday", value: "friday" },
          { label: "Saturday", value: "saturday" },
          { label: "Sunday", value: "sunday" },
        ],
        step: 1,
        order: 26.6,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-custom-days",
            triggerFieldId: "field-working-days-preset",
            operator: "equals",
            value: "custom",
            action: "show",
            targetFieldIds: ["field-working-days"],
          },
        ],
      },
      {
        id: "field-weekly-hours",
        name: "weeklyHours",
        label: "Weekly Hours",
        type: "number",
        required: true,
        step: 1,
        order: 27,
        width: "half",
      },
      {
        id: "field-break-minutes",
        name: "breakMinutes",
        label: "Break Duration (minutes)",
        type: "number",
        required: true,
        defaultValue: "60",
        helperText: "Default is 60 minutes (1 hour)",
        step: 1,
        order: 27.5,
        width: "half",
      },
      {
        id: "field-salary",
        name: "salary",
        label: "Annual Salary (£)",
        type: "number",
        required: true,
        helperText: "For contractors, enter estimated annual value",
        step: 1,
        order: 28,
        width: "half",
      },
      {
        id: "field-vacation-days",
        name: "vacationDays",
        label: "Annual Vacation Days",
        type: "number",
        required: false,
        helperText: "Number of vacation/holiday days per year",
        step: 1,
        order: 28.5,
        width: "half",
      },
      {
        id: "field-hourly-rate",
        name: "hourlyRate",
        label: "Hourly Rate (£)",
        type: "number",
        required: true,
        helperText: "Required for all employees (enter 0 if not applicable)",
        step: 1,
        order: 29,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-hourly",
            triggerFieldId: "field-contract-type",
            operator: "equals",
            value: "contractor",
            action: "show",
            targetFieldIds: ["field-hourly-rate"],
          },
        ],
      },
      {
        id: "field-paye",
        name: "payeReference",
        label: "PAYE Reference",
        type: "text",
        helperText: "Auto-populated from SL Issuance data when available (read-only)",
        step: 1,
        order: 30,
        width: "half",
      },
      {
        id: "field-national-insurance",
        name: "nationalInsurance",
        label: "National Insurance Number",
        type: "text",
        helperText: "Provide now or select a timeframe below",
        step: 1,
        order: 31,
        width: "half",
      },
      {
        id: "field-national-insurance-later",
        name: "nationalInsuranceProvideLater",
        label: "Provide NI Number Later",
        type: "select",
        helperText: "If not providing now, select when you'll provide it",
        defaultValue: "providing_now",
        options: [
          { label: "Providing now", value: "providing_now" },
          { label: "In 1 week", value: "1_week" },
          { label: "In 2 weeks", value: "2_weeks" },
          { label: "In 3 weeks", value: "3_weeks" },
          { label: "In 4 weeks", value: "4_weeks" },
          { label: "In 5 weeks", value: "5_weeks" },
          { label: "In 6 weeks", value: "6_weeks" },
        ],
        step: 1,
        order: 32,
        width: "half",
      },
      {
        id: "field-google-drive-link",
        name: "googleDriveLink",
        label: "Google Drive Link",
        type: "text",
        required: true,
        helperText: "Link to employee's document folder (required)",
        placeholder: "https://drive.google.com/...",
        step: 1,
        order: 33,
        width: "full",
      },
      
      // =========================================
      // STEP 2: NATIONALITY/STATUS QUESTION
      // =========================================
      {
        id: "field-immigration-status",
        name: "immigrationStatus",
        label: "What is the employee's nationality/status?",
        type: "radio",
        required: true,
        options: [
          { label: "British", value: "british" },
          { label: "Settled (ILR/Settled Status)", value: "settled" },
          { label: "Other (Non-British)", value: "other" },
        ],
        step: 2,
        order: 1,
        width: "full",
      },
      
      // =========================================
      // STEP 3: CONDITIONAL BLOCKS
      // =========================================
      
      // BRITISH PATHWAY
      {
        id: "header-british-rtw",
        name: "header_british_rtw",
        label: "Right to Work Check (Record Only)",
        type: "section_header",
        step: 3,
        order: 1,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-british-rtw-header",
            triggerFieldId: "field-immigration-status",
            operator: "equals",
            value: "british",
            action: "show",
            targetFieldIds: ["header-british-rtw"],
          },
        ],
      },
      {
        id: "field-rtw-check-date-british",
        name: "rtwCheckDate",
        label: "RTW Check Date",
        type: "date",
        step: 3,
        order: 2,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-rtw-date-british",
            triggerFieldId: "field-immigration-status",
            operator: "equals",
            value: "british",
            action: "show",
            targetFieldIds: ["field-rtw-check-date-british"],
          },
        ],
      },
      {
        id: "info-british-indefinite",
        name: "info_british_indefinite",
        label: "RTW Expiry: Indefinite (British citizens have permanent right to work)",
        type: "info_text",
        step: 3,
        order: 3,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-british-info",
            triggerFieldId: "field-immigration-status",
            operator: "equals",
            value: "british",
            action: "show",
            targetFieldIds: ["info-british-indefinite"],
          },
        ],
      },
      
      // SETTLED PATHWAY
      {
        id: "header-settled-docs",
        name: "header_settled_docs",
        label: "Settlement Documentation",
        type: "section_header",
        step: 3,
        order: 4,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-settled-section",
            triggerFieldId: "field-immigration-status",
            operator: "equals",
            value: "settled",
            action: "show",
            targetFieldIds: ["header-settled-docs"],
          },
        ],
      },
      {
        id: "field-brp-share-code-settled",
        name: "brpShareCode",
        label: "BRP/Share Code (Optional)",
        type: "text",
        step: 3,
        order: 5,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-brp-settled",
            triggerFieldId: "field-immigration-status",
            operator: "equals",
            value: "settled",
            action: "show",
            targetFieldIds: ["field-brp-share-code-settled"],
          },
        ],
      },
      {
        id: "header-settled-rtw",
        name: "header_settled_rtw",
        label: "Right to Work Check",
        type: "section_header",
        step: 3,
        order: 11,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-settled-rtw-header",
            triggerFieldId: "field-immigration-status",
            operator: "equals",
            value: "settled",
            action: "show",
            targetFieldIds: ["header-settled-rtw"],
          },
        ],
      },
      {
        id: "field-rtw-check-date-settled",
        name: "rtwCheckDate",
        label: "RTW Check Date",
        type: "date",
        step: 3,
        order: 12,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-rtw-date-settled",
            triggerFieldId: "field-immigration-status",
            operator: "equals",
            value: "settled",
            action: "show",
            targetFieldIds: ["field-rtw-check-date-settled"],
          },
        ],
      },
      {
        id: "field-rtw-evidence-settled",
        name: "rtwEvidenceType",
        label: "Evidence Type",
        type: "select",
        options: [
          { label: "BRP", value: "brp" },
          { label: "Share Code", value: "share_code" },
        ],
        step: 3,
        order: 13,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-evidence-settled",
            triggerFieldId: "field-immigration-status",
            operator: "equals",
            value: "settled",
            action: "show",
            targetFieldIds: ["field-rtw-evidence-settled"],
          },
        ],
      },
      {
        id: "info-settled-indefinite",
        name: "info_settled_indefinite",
        label: "RTW Expiry: Indefinite (Settled status provides permanent right to work)",
        type: "info_text",
        step: 3,
        order: 14,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-settled-info",
            triggerFieldId: "field-immigration-status",
            operator: "equals",
            value: "settled",
            action: "show",
            targetFieldIds: ["info-settled-indefinite"],
          },
        ],
      },
      
      // OTHER (NON-BRITISH) PATHWAY - Ask Sponsored/Non-Sponsored
      {
        id: "field-is-sponsored",
        name: "isSponsored",
        label: "Is the employee sponsored by the company?",
        type: "radio",
        options: [
          { label: "Sponsored", value: "true" },
          { label: "Non-Sponsored (has own right to work)", value: "false" },
        ],
        step: 3,
        order: 15,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-sponsored-question",
            triggerFieldId: "field-immigration-status",
            operator: "equals",
            value: "other",
            action: "show",
            targetFieldIds: ["field-is-sponsored"],
          },
        ],
      },
      
      // SPONSORED PATHWAY
      {
        id: "header-visa-sponsorship",
        name: "header_visa_sponsorship",
        label: "Sponsorship & Visa Details",
        type: "section_header",
        step: 3,
        order: 16,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-sponsor-section",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["header-visa-sponsorship"],
          },
        ],
      },
      {
        id: "field-visa-type",
        name: "visaType",
        label: "Visa Type",
        type: "text",
        required: true,
        placeholder: "e.g., Skilled Worker",
        step: 3,
        order: 17,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-visa-type",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["field-visa-type"],
          },
        ],
      },
      {
        id: "field-cos-number",
        name: "cosNumber",
        label: "COS Number",
        type: "text",
        required: true,
        step: 3,
        order: 18,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-cos",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["field-cos-number"],
          },
        ],
      },
      {
        id: "field-sponsor-license",
        name: "sponsorLicenseNumber",
        label: "Sponsor License Number",
        type: "text",
        required: true,
        helperText: "Auto-filled from company if available",
        step: 3,
        order: 19,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-sponsor-license",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["field-sponsor-license"],
          },
        ],
      },
      {
        id: "field-visa-issue-date",
        name: "visaIssueDate",
        label: "Visa Issue Date",
        type: "date",
        required: true,
        step: 3,
        order: 20,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-visa-issue",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["field-visa-issue-date"],
          },
        ],
      },
      {
        id: "field-visa-expiry-date",
        name: "visaExpiryDate",
        label: "Visa Expiry Date",
        type: "date",
        required: true,
        step: 3,
        order: 21,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-visa-expiry",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["field-visa-expiry-date"],
          },
        ],
      },
      {
        id: "header-sponsored-rtw",
        name: "header_sponsored_rtw",
        label: "Right to Work Check",
        type: "section_header",
        step: 3,
        order: 24,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-sponsored-rtw-header",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["header-sponsored-rtw"],
          },
        ],
      },
      {
        id: "field-rtw-check-date-sponsored",
        name: "rtwCheckDate",
        label: "RTW Check Date",
        type: "date",
        step: 3,
        order: 25,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-rtw-sponsored",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["field-rtw-check-date-sponsored"],
          },
        ],
      },
      {
        id: "field-rtw-evidence-sponsored",
        name: "rtwEvidenceType",
        label: "Evidence Type",
        type: "select",
        options: [
          { label: "BRP", value: "brp" },
          { label: "Share Code", value: "share_code" },
        ],
        step: 3,
        order: 26,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-evidence-sponsored",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["field-rtw-evidence-sponsored"],
          },
        ],
      },
      {
        id: "field-rtw-expiry-mode-sponsored",
        name: "rtwExpiryDateMode",
        label: "RTW Expiry Date",
        type: "select",
        required: true,
        defaultValue: "auto",
        options: [
          { label: "Auto-set to match visa expiry", value: "auto" },
          { label: "Manual", value: "manual" },
        ],
        step: 3,
        order: 27,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-rtw-expiry-mode-sponsored",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["field-rtw-expiry-mode-sponsored"],
          },
        ],
      },
      {
        id: "field-rtw-expiry-date-manual-sponsored",
        name: "rtwExpiryDate",
        label: "RTW Expiry Date (Manual)",
        type: "date",
        helperText: "Enter specific RTW expiry date",
        step: 3,
        order: 28,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-rtw-manual-sponsored",
            triggerFieldId: "field-rtw-expiry-mode-sponsored",
            operator: "equals",
            value: "manual",
            action: "show",
            targetFieldIds: ["field-rtw-expiry-date-manual-sponsored"],
          },
        ],
      },
      {
        id: "info-sponsored-auto-calc",
        name: "info_sponsored_auto_calc",
        label: "When Auto is selected, RTW expiry will match visa expiry. Next RTW check will be auto-calculated as 90 days before expiry.",
        type: "info_text",
        step: 3,
        order: 29,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-sponsored-info",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["info-sponsored-auto-calc"],
          },
        ],
      },
      
      // NON-SPONSORED PATHWAY
      {
        id: "header-non-sponsored-rtw",
        name: "header_non_sponsored_rtw",
        label: "Right to Work Details",
        type: "section_header",
        step: 3,
        order: 28,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-non-sponsored-section",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "false",
            action: "show",
            targetFieldIds: ["header-non-sponsored-rtw"],
          },
        ],
      },
      {
        id: "field-rtw-basis",
        name: "rtwBasis",
        label: "Basis of Right to Work",
        type: "select",
        options: [
          { label: "Dependant", value: "dependant" },
          { label: "Graduate", value: "graduate" },
          { label: "Student", value: "student" },
          { label: "EU Pre-settled", value: "eu_presettled" },
          { label: "Other", value: "other" },
        ],
        step: 3,
        order: 29,
        width: "full",
        conditionalRules: [
          {
            id: "rule-show-rtw-basis",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "false",
            action: "show",
            targetFieldIds: ["field-rtw-basis"],
          },
        ],
      },
      {
        id: "field-rtw-evidence-non-sponsored",
        name: "rtwEvidenceType",
        label: "Evidence Type",
        type: "select",
        options: [
          { label: "Passport", value: "passport" },
          { label: "BRP", value: "brp" },
          { label: "Share Code", value: "share_code" },
        ],
        step: 3,
        order: 30,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-evidence-non-sponsored",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "false",
            action: "show",
            targetFieldIds: ["field-rtw-evidence-non-sponsored"],
          },
        ],
      },
      {
        id: "field-rtw-check-date-non-sponsored",
        name: "rtwCheckDate",
        label: "RTW Check Date",
        type: "date",
        step: 3,
        order: 31,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-rtw-date-non-sponsored",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "false",
            action: "show",
            targetFieldIds: ["field-rtw-check-date-non-sponsored"],
          },
        ],
      },
      {
        id: "field-rtw-expiry-non-sponsored",
        name: "rtwExpiryDate",
        label: "RTW Expiry Date",
        type: "date",
        helperText: "Provide expiry date or check indefinite box below",
        step: 3,
        order: 32,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-rtw-expiry-non-sponsored",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "false",
            action: "show",
            targetFieldIds: ["field-rtw-expiry-non-sponsored"],
          },
        ],
      },
      {
        id: "field-rtw-expiry-indefinite",
        name: "rtwExpiryIndefinite",
        label: "RTW is Indefinite (No Expiry)",
        type: "checkbox",
        helperText: "Check if right to work has no expiry date",
        step: 3,
        order: 33,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-rtw-indefinite",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "false",
            action: "show",
            targetFieldIds: ["field-rtw-expiry-indefinite"],
          },
        ],
      },
      {
        id: "field-rtw-share-code",
        name: "rtwShareCode",
        label: "Share Code (Optional)",
        type: "text",
        helperText: "Note: Share codes are valid for 30 days",
        step: 3,
        order: 33,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-share-code",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "false",
            action: "show",
            targetFieldIds: ["field-rtw-share-code"],
          },
        ],
      },
      
      // =========================================
      // STEP 4: COMPLIANCE & DOCUMENTS (always shown)
      // =========================================
      {
        id: "header-compliance",
        name: "header_compliance",
        label: "Compliance & Status",
        type: "section_header",
        step: 4,
        order: 1,
        width: "full",
      },
      {
        id: "field-probation-period",
        name: "probationPeriod",
        label: "Probation Period (Months)",
        type: "number",
        defaultValue: 3,
        step: 4,
        order: 2,
        width: "half",
        autoCalculate: {
          formula: "probation_end",
          dependencies: ["field-start-date", "field-probation-period"],
        },
      },
      {
        id: "info-probation-auto",
        name: "info_probation_auto",
        label: "Probation end date will be auto-calculated from start date + probation period",
        type: "info_text",
        step: 4,
        order: 3,
        width: "full",
      },
      {
        id: "field-status",
        name: "status",
        label: "Employee Status",
        type: "select",
        defaultValue: "onboarding",
        options: [
          { label: "Onboarding", value: "onboarding" },
          { label: "Active", value: "active" },
          { label: "On Hold", value: "on_hold" },
          { label: "Leaver", value: "leaver" },
        ],
        step: 4,
        order: 4,
        width: "half",
      },
      {
        id: "field-ukvi-notes",
        name: "ukviReportingNotes",
        label: "UKVI Reporting Notes",
        type: "textarea",
        helperText: "Any notes regarding UKVI compliance or reporting requirements",
        step: 4,
        order: 5,
        width: "full",
      },
      {
        id: "header-documents",
        name: "header_documents",
        label: "Document Verification - Confirm Copies Kept",
        type: "section_header",
        step: 4,
        order: 6,
        width: "full",
      },
      {
        id: "info-documents",
        name: "info_documents",
        label: "Tick the boxes below to confirm you have kept copies of the following documents:",
        type: "info_text",
        step: 4,
        order: 7,
        width: "full",
      },
      {
        id: "field-doc-passport",
        name: "docPassportCopy",
        label: "Passport Copy",
        type: "checkbox",
        step: 4,
        order: 8,
        width: "half",
      },
      {
        id: "field-doc-graduation",
        name: "docGraduationCertCopy",
        label: "Graduation Certificate Copy",
        type: "checkbox",
        step: 4,
        order: 9,
        width: "half",
      },
      {
        id: "field-doc-proof-address",
        name: "docProofOfAddressCopy",
        label: "Proof of Address Copy",
        type: "checkbox",
        step: 4,
        order: 10,
        width: "half",
      },
      {
        id: "field-doc-rtw",
        name: "docRtwCopy",
        label: "RTW Document Copy",
        type: "checkbox",
        helperText: "Only if RTW check required",
        step: 4,
        order: 11,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-rtw-doc",
            triggerFieldId: "field-immigration-status",
            operator: "not_equals",
            value: "british",
            action: "show",
            targetFieldIds: ["field-doc-rtw"],
          },
        ],
      },
      {
        id: "field-doc-cos",
        name: "docCosCopy",
        label: "COS Copy",
        type: "checkbox",
        helperText: "Only if employee is sponsored",
        step: 4,
        order: 12,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-cos-doc",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["field-doc-cos"],
          },
        ],
      },
      {
        id: "field-doc-visa",
        name: "docVisaCopy",
        label: "Visa Copy",
        type: "checkbox",
        helperText: "Only if employee has visa",
        step: 4,
        order: 13,
        width: "half",
        conditionalRules: [
          {
            id: "rule-show-visa-doc",
            triggerFieldId: "field-is-sponsored",
            operator: "equals",
            value: "true",
            action: "show",
            targetFieldIds: ["field-doc-visa"],
          },
        ],
      },
    ],
    globalRules: [],
    createdAt: now,
    updatedAt: now,
  };
}
